import * as Yup from "yup";

export const initialValues = {
  fullName: "",
  age: "",
  birthDate: "",
  placeOfBirth: "",
  nationality: "",
  identityDocument: "",
  maritalStatus: "",
  numberOfChildren: "",
  address: "",
  neighborhood: "",
  city: "",
  phone: "",
  email: "",
  ownVehicle: "",
  vehicleType: "",
  appliedPosition: "",
  // :::::CONTEXTO FAMILIAR:::::
  mother: "",
  father: "",
  spouse: "",
  spouseName: "",
  siblingsAges: "",
  livingWith: "",
  // :::::CONTEXTO ACADEMICO:::::
  primarySchool: "",
  highSchool: "",
  university: "",
  major: "",
  year: "",
  // :::::OTROS CONOCIMIENTOS:::::
  spanish_lenguages: "",
  guarani_lenguages: "",
  english_lenguages: "",
  portuguese_lenguages: "",
  other01: "",
  other01_select: "",
  other02_advanced: "",
  processorText: "",
  electronicSpreadsheets: "",
  presentations: "",
  email_: "",
  other03: "",
  // :::::INTERES:::::
  area01: "",
  area02: "",
  area03: "",
  min: "",
  max: "",
  incorporation: "",
};

export const validationSchema = Yup.object().shape({
  fullName: Yup.string().trim().required("Este campo es requerido"),
  age: Yup.number().integer().required("Este campo es requerido"),
  birthDate: Yup.string().required("Este campo es requerido"),
  placeOfBirth: Yup.string().required("Este campo es requerido"),
  nationality: Yup.string().required("Este campo es requerido"),
  identityDocument: Yup.string().required("Este campo es requerido"),
  maritalStatus: Yup.string().required("Este campo es requerido"),
  numberOfChildren: Yup.string().required("Este campo es requerido"),
  address: Yup.string().required("Este campo es requerido"),
  neighborhood: Yup.string().required("Este campo es requerido"),
  city: Yup.string().required("Este campo es requerido"),
  phone: Yup.string().required("Este campo es requerido"),
  email: Yup.string()
    .email("Formato de email inválido")
    .required("Este campo es requerido"),
  ownVehicle: Yup.string().required("Este campo es requerido"),
  vehicleType: Yup.string().required("Este campo es requerido"),
  appliedPosition: Yup.string().required("Este campo es requerido"),
  // :::::CONTEXTO FAMILIAR:::::
  mother: Yup.string().required("El campo es requerido"),
  father: Yup.string().required("El campo es requerido"),
  spouse: Yup.string().required("El campo es requerido"),
  spouseName: Yup.string().required("El campo es requerido"),
  siblingsAges: Yup.string().required("El campo es requerido"),
  livingWith: Yup.string().required("El campo es requerido"),
  // :::::CONTEXTO ACADEMICO:::::
  primarySchool: Yup.string().trim().required("El campo es querido"),
  highSchool: Yup.string().trim().required("El campo es querido"),
  university: Yup.string().trim().required("El campo es querido"),
  major: Yup.string().trim().required("El campo es querido"),
  year: Yup.string().trim().required("El campo es querido"),
  // :::::OTROS CONOCIMIENTOS:::::
  spanish_lenguages: Yup.string().required("Selecciona al menos una opción"),
  guarani_lenguages: Yup.string().required("Selecciona al menos una opción"),
  english_lenguages: Yup.string().required("Selecciona al menos una opción"),
  portuguese_lenguages: Yup.string().required("Selecciona al menos una opción"),
  other01: Yup.string().trim().required("El campo es querido"),
  other01_select: Yup.string().required("Este campo es requerido"),
  processorText: Yup.string().required("Selecciona al menos una opción"),
  electronicSpreadsheets: Yup.string().required(
    "Selecciona al menos una opción"
  ),
  presentations: Yup.string().required("Selecciona al menos una opción"),
  email_: Yup.string().required("Selecciona al menos una opción"),
  other03: Yup.string().trim().required("Este campo es requerido"),
  // :::::INTERES:::::
  area01: Yup.string().required("El campo es requerido"),
  area02: Yup.string().required("El campo es requerido"),
  area03: Yup.string().required("El campo es requerido"),
  min: Yup.string().trim().required("El campo es requerido"),
  max: Yup.string().trim().required("El campo es requerido"),
  incorporation: Yup.string().trim().required("El campo es requerido"),
});
